name: "Tests"

on:
  push:
    branches:
      - master
      - main

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1
    strategy:
      fail-fast: false
      matrix:
        build: [ x86_64-windows ] # Handles both msvc and gnu
        include:
          - build: 86_64-pc-windows-msvc
            os: windows-latest
            repository: csv_parser_rs
            rust: nightly
            target: x86_64-pc-windows-msvc
            cross: false
          - build: 86_64-pc-windows-gnu
            repository: csv_parser_rs
            os: windows-latest
            rust: nightly
            target: x86_64-pc-windows-gnu
            cross: false
    steps:
      - name: Checkout sources
        uses: actions/checkout@master

      - name: Remove rust-toolchain.toml file
        run: rm rust-toolchain.toml

      - name: Setup Rust for {{ matrix.os }} using {{ matrix.rust }} toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly
          target: ${{ matrix.target }}
          components: rustfmt, clippy, cargo, rustc-codegen-cranelift

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true

      - name: Run cargo test
        run: cargo test --all

      - name: Run cargo test
        run: cargo test --release --all
